services:

  backend_test:
    container_name: backend_test
    build:
      context: ./backend
      dockerfile: Dockerfile_backend_test
    volumes:
      - ./backend:/backend
    environment:
      DATABASE: database_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    networks:
      - web_app_network
    ports:
      - '127.0.0.1:8000:8000'
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      database_test:
        condition: service_healthy

  database_test:
    image: postgres:15-alpine3.18
    container_name: database_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - web_app_network
    restart: always


networks:
  web_app_network:
    driver: bridge
