"""change type for user_id

Revision ID: 9ba300fbd7ff
Revises: 1d744b7e61ed
Create Date: 2023-11-28 08:36:08.303082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba300fbd7ff'
down_revision: Union[str, None] = '1d744b7e61ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
