"""alter table passwords

Revision ID: 1d744b7e61ed
Revises: 
Create Date: 2023-11-27 10:28:46.513239

"""
from typing import Sequence, Union
import db
from alembic import op
import sqlalchemy as sa


revision: str = '1d744b7e61ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), server_default='7f3996fa-82d2-4132-aa22-6495dbe8ddb9', nullable=False),
    sa.Column('login', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('password', db.passwords.models.HexByteString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwords')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
